# Generated by Django 4.1 on 2022-09-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productshopify",
            name="image_id",
            field=models.IntegerField(null=True),
        ),
    ]
