# Generated by Django 4.1 on 2022-09-13 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_alter_productshopify_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productshopifyvariant",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="src.productshopifyimage",
            ),
        ),
    ]
