# Generated by Django 4.1 on 2022-09-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_productcategory_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.TextField(null=True),
        ),
    ]
